### ISSUE TITLE
Leaked Credentials

### ISSUE THREAD

**Issue by tulhan** [yuta519/zscaler-admin-app#3]
Hello Yuta-san,

I am a part of the Zscaler security team. We were alerted that you had checked in credentials for the ZIA portal in this repo at sample/sample_adminuser.json.

While I couldn't find any account in zscaler.net cloud associated with this account, I urge you to consider whether this information needs to be public.

**Comment by yuta519** [comment]
Hi, Naresh

Thanks for contacting me. Sorry for credentials of my json file.

The file you mentioned has below username.
> yuta.kawamura@zscaler.net

But this is a not real ZIA account.
I added this info to explain how to use this file as sample.

Although I think this is not confidential info, I'll change this domain from zscaler.net to like sample.com.
